# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d06a6271fa764bae7d5ad4f6afbafe172035661bf183f4180e5a5b17ecb017a798a11200ecdf441b28d532d7a0b755ff22a91e00a06bdff9907b82f195d923

test:
  secret_key_base: 3085b6e733c0aef84b4c8a70060a69bec1e5de16b51983478dac8948adbef834bd9e2c25c40ae1085acdcf6f76d8c4f384db3b11c0f49ac707e39ded3be9e692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
